- id: '1612625540203'
  alias: SWITCH caldaia OFF ---> spegnimento termostati
  description: ''
  trigger:
  - platform: state
    entity_id: switch.caldaia
    to: 'off'
  condition: []
  action:
  - service: climate.turn_off
    data: {}
    entity_id: climate.casa_bagno_termostato
  - service: climate.turn_off
    data: {}
    entity_id: climate.casa_sala_termostato
  - service: climate.turn_off
    data: {}
    entity_id: climate.casa_zona_notte_termostato
  - service: switch.turn_off
    data: {}
    entity_id: switch.pompa_laboratorio
  mode: single
- id: '1612718511945'
  alias: se SWITCH caldaia OFF ogni ora alle .25 ---> spegnimento termostati
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '25'
  condition:
  - condition: state
    entity_id: switch.caldaia
    state: 'off'
  action:
  - service: climate.turn_off
    data: {}
    entity_id: climate.casa_bagno_termostato
  - service: climate.turn_off
    data: {}
    entity_id: climate.casa_sala_termostato
  - service: climate.turn_off
    data: {}
    entity_id: climate.casa_zona_notte_termostato
  - service: switch.turn_off
    data: {}
    entity_id: switch.pompa_laboratorio
  - service: switch.turn_off
    data: {}
    entity_id: switch.pompa_zona_notte
  mode: single
- id: '1613232519028'
  alias: se Sensor/1/status=offline --> spengo termostato sala + notifica
  description: ''
  trigger:
  - platform: mqtt
    topic: home-assistant/sensor/1/status
    payload: offline
  condition: []
  action:
  - service: climate.turn_off
    data: {}
    entity_id: climate.casa_sala_termostato
  - service: notify.mobile_app_nexus_5x
    data:
      title: Sensore OFFLINE!!
      message: il sensore sala è offline
  - service: notify.mobile_app_mi_9_se
    data:
      title: Sensore OFFLINE!!
      message: il sensore sala è offline
  mode: single
- id: '1613233279494'
  alias: se Sensor/2/status=offline --> spengo termostato notte + notifica
  description: ''
  trigger:
  - platform: mqtt
    topic: home-assistant/sensor/2/status
    payload: offline
  condition: []
  action:
  - service: climate.turn_off
    data: {}
    entity_id: climate.casa_zona_notte_termostato
  - service: notify.mobile_app_nexus_5x
    data:
      title: Sensore OFFLINE!!
      message: il sensore zona notte è offline
  - service: notify.mobile_app_mi_9_se
    data:
      title: Sensore OFFLINE!!
      message: il sensore zona notte è offline
  mode: single
- id: '1613233348661'
  alias: se Sensor/3/status=offline --> spengo termostato bagno
  description: ''
  trigger:
  - platform: mqtt
    topic: home-assistant/sensor/3/status
    payload: offline
  condition: []
  action:
  - service: climate.turn_off
    data: {}
    entity_id: climate.casa_bagno_termostato
  - service: notify.mobile_app_nexus_5x
    data:
      title: Sensore OFFLINE!!
      message: il sensore bagno è offline
  - service: notify.mobile_app_mi_9_se
    data:
      title: Sensore OFFLINE!!
      message: il sensore bagno è offline
  mode: single
